development:
  adapter: postgresql
  encoding: unicode
  database: recyle_development
  pool: 5
  timeout: 5000
  username: postgres
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: recyle_test
  pool: 5
  timeout: 5000
  username: postgres
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  database: recyle_production
  pool: 5
  timeout: 5000
  username: postgres
  password: admin
